version: '3.8' # Versión del motor de Docker Compose

services:
  db: # Nombre del servicio
    image: postgres:15 # Usamos la imagen oficial de PostgreSQL versión 15
    container_name: postgres_telco # Nombre que tendrá tu contenedor en Docker
    restart: always # Si la PC se reinicia, el contenedor también
    environment:
      # Definimos las credenciales de acceso a la base de datos
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_password
      POSTGRES_DB: telco_db # Nombre de la base de datos que se creará
    ports:
      - "5432:5432" # Conecta el puerto 5432 de tu PC con el del contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data # Para que los datos no se borren al apagar Docker

volumes:
  postgres_data: # Espacio de almacenamiento persistente